# Generated by Django 5.1 on 2024-08-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_task_duedate_alter_task_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dueDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
