# Generated by Django 5.1 on 2024-09-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_task_duedate_alter_task_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='favorite',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
